[package]
name = "log-collection-client"
version = "0.1.0"
edition = "2021"

[lib]
name = "s3_service"
path = "src/s3-service-lib.rs"

[dependencies]
aws-config = { version= "1.1.1", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.9.0"
aws-sdk-s3= { version = "1.11.0", features = ["rt-tokio"] }
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
aws-smithy-types= { version = "1.1.1", features = ["http-body-0-4-x"] }

[dependencies.clap]
version = "~4.4"
features = ["derive"]

[dependencies.uuid]
version = "1.3.1"
features = ["serde", "v4"]
