[package]
name = "log-collection-client"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version= "1.1.1", features = ["behavior-version-latest"] }
tokio = { version = "1", features = ["full"] }
aws-sdk-firehose = "1.10.0"
aws-sdk-kinesis = "1.10.0"
