# configuration for log collection
# https://toml.io/en/v1.0.0#array-of-tables

[dynamodb]

[[dynamodb.package]]
source = "test1.log"
table = "SecurityLog1"

[[dynamodb.package]]
source = "test2.log"
table = "SecurityLog2"

[[dynamodb.package]]
source = "test3.log"
table = "SecurityLog3"